### ISSUE TITLE
Nick Wilcox Response

### ISSUE THREAD

**Issue by nwilcox11** [ga-wdi-boston/html-css-layout-study#10]
1. Originally when you set the width of an element, it may appear larger than you think.  This is because of padding and the border.  At one point you had to keep track of the px of padding and borders you were adding to the total px.  With Box-sizing this is no longer necessary.  When you set box-sizing: border-box, padding and border no longer affect width. 
2. Relative position behaves the same as static positioning, unless you add extra properties like right, left, bottom, top.  Absolute positioning behaves like fixed, except rather than being positioned relative to the view point, it is positioned relative to its nearest ancestor or the document body.  If it uses the document body, it will still move when the page is scrolled.
3.  3 gotchas = 1. having images that are taller than their containers
                         2. writing css that is not supported by some browsers
                         3. setting the width element without accounting for padding and margins...unless you use             box sizing.

**Comment by J-Weeks** [comment]
Good job.
