### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by erdesi90562** [ga-wdi-boston/html-css-layout-study#11]
What is the different options for box-sizing? Explain the differences between them.

box-sizing has border-box and content-box as options.
The option of border-box controls the width and height properties along with padding and border.
The content-box is the default setting but it controls the width and height properties are measure including only the content.

In your own words, explain the difference between relative and absolute positioning.

The differenct between relative and absolute is the absolute position makes that element's position relative to its ancestor. The relative position is in referance to the elements normal position.

What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better.
The gotchas.
1. specificity
2. Inheritance
3. spelling errors

**Comment by J-Weeks** [comment]
Nice, good job, keep up the good work.
