### ISSUE TITLE
A.Jordon Response

### ISSUE THREAD

**Issue by ajordon** [ga-wdi-boston/html-css-layout-study#12]
1) Content-box: When altering width and height properties, this only is measured by the content of the element and does not include padding, border or margin. 
Border-box: When altering width and height properties, both the padding and border are being changed. The element is also not affected be margin changes.

2) Relative position is a new position relative to its normal static position while absolute position is positioned relative to its parent. 

3)Floating and forgetting to clear the next element. 
Not designing for mobile first.
Not setting "vertical-align: top;" when utilizing an inline-block elements

**Comment by J-Weeks** [comment]
Nice.  Keep up the good work.
