### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by seatuna** [ga-wdi-boston/html-css-layout-study#13]
1. What are the different options for box-sizing? Explain the differences between them.
The options are 1) doing math, or 2) using the new box-sizing CSS selector.  In the past, people created elements and could set a width to control the size of the box element.  However, if you wanted to add padding, margins, or borders, they would occur around the element which stretched the actual width of the element.  Thus, the width of the element would not be the specified number, but that number + padding + margins + border.  As a result, another element with the same width but no margins / padding / borders would appear to be smaller.  In order to get those 2 boxes to appear the same size, people had to subtract margins etc from the desired width and set that difference as the width.  Option 2 is using the box-sizing CSS selector, which allows you to have all your margins / padding / borders in your element so that it does not stretch the element.

2. In your own words, explain the difference between relative and absolute positioning.
Relative positioning allows an element to be positioned at a different part of the page than where it would be expected to go, by setting the values for top / left / bottom / right.  These values will refer to the area on the page that the relatively positioned element would normally go if it were in static position.  Absolute positioning also allows the same thing to happen, but has a different reference point.  It will use the closest prior positioned element as a reference point to add or subtract the values of top / left / bottom / right.

3. What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better.
* Forgetting to clear after using floating elements
* Moving an absolutely positioned element to the wrong place because you had the wrong positioned ancestor element in mind
* In media queries, having an element too narrow resulting in its contents getting too squished

**Comment by J-Weeks** [comment]
Good. I think you have the right idea but it's a bit difficult for me to understand the language you used in your second response.  I think you have a good grasp of this though.
