### ISSUE TITLE
study.md doesn't follow the template

### ISSUE THREAD

**Issue by bernardlee** [ga-wdi-boston/html-css-layout-study#137]
[`study.md`](study.md) should follow the same format as [`study.md`](https://github.com/ga-wdi-boston/study-template/blob/master/study.md) in [Study Template](https://github.com/ga-wdi-boston/study-template).

**Comment by jordanallain** [comment]
addressed by commit 7373c36d4e1f8ab76e7a049ef7c14191bb1259fb
