### ISSUE TITLE
Response 

### ISSUE THREAD

**Issue by Knguyen21** [ga-wdi-boston/html-css-layout-study#14]
- What is the different options for box-sizing? Explain the differences between them.
    - -webkit and -moz are prefixes which allows experimental features in specific browser.
    - border-box: the padding and border of that element no longer increase its width.

- In your own words, explain the difference between relative and absolute positioning.
    - relative position is relative to it’s normal position. Whereas, absolute position is relative to the nearest positioned ancestor instead of the relative to the view window.

- What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better.
    - 1.  When using floats, the element you are floating might be taller than the element containing it, and it's overfloating outside of its container
    - 2. When setting a width to a certain pixel, there might be an issue is the browser window is narrower than the width of the element.
    - 3.When you set the width of an element, the element can actually appear bigger than what you set: the element's border and padding will stretch out the element beyond the specified width.

**Comment by J-Weeks** [comment]
Review your understanding of border box, content box...
