### ISSUE TITLE
CSS layout

### ISSUE THREAD

**Issue by apalmer0** [ga-wdi-boston/html-css-layout-study#15]
What is the different options for box-sizing? Explain the differences between them.
content-box, border-box: both expand height and width to contain the content, but border-box includes padding and border.

In your own words, explain the difference between relative and absolute positioning.
elements placed with relative positioning are positioned relative to themselves; if there are no modifiers passed, they will appear just like statically-positioned elements. if there are modifiers, they will appear relative to where they normally would have appeared. elements placed with absolute positioning appear relative to the first parent element with relative positioning, or relative to the document itself if there is no such element. 

What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better.
confusing relative and absolute positioning (or any other positioning), not styling content to resize for all browser window sizes, using inline css

**Comment by J-Weeks** [comment]
Nice, all correct good job.
