### ISSUE TITLE
Response

### ISSUE THREAD

**Issue by jdamiron** [ga-wdi-boston/html-css-layout-study#16]
1. The keyword values for box-sizing are content-box and border-box. Content-box measures the width and height properties using only the related content and doesn't account for the margin, border, or padding. Border-box includes the padding and border, but not the margin.

2. Relative positioning means an element's position is set relative to it's own position, meaning a new position is created off of it's initial positioning. Absolute positioning allows you to position an element anywhere, it is also relative to it's parent element, if there isn't one available, it becomes relative to the page itself.

3. Designing a web page for bigger screens first and then designing for smaller scaled screens.
Having selectors overwrite each other based on how far up or down they are in the css file.
Not using units to measure elements properly. Ex. Using px instead of em.

**Comment by J-Weeks** [comment]
Good job.
