### ISSUE TITLE
James Friedman Response

### ISSUE THREAD

**Issue by jpfriedman18** [ga-wdi-boston/html-css-layout-study#17]
1) The (non-global) box-sizing options are: border-box and content-box. The border-box value sets an element such that padding and border are included in the total width and height values. The content-box option sets an element's height and width to only include the content, but not the padding, border, or margin.
2)Relative positioning is essentially the same as static positioning (where something will stay in the same place on the page and move as the user scrolls along the page). Absolute positioning allows something to stay in the same place in the window as the user scrolls (like fixed positioning), BUT it's position is determined by it's parent element, rather than the window.
3) Gotchas: If an image is floated but is too large for it's container, it can overflow out of that container; making rows of boxes using float requires using clear to make sure things don't collide on the same line, instead you should just use inline-block so that you don't have to remember to use clear; not sure what the third was...

**Comment by J-Weeks** [comment]
Nice, you have a grasp on this.  Good job.
