### ISSUE TITLE
html-css-layout-study 

### ISSUE THREAD

**Issue by msyao-github** [ga-wdi-boston/html-css-layout-study#18]
What are the different options for box-sizing? Explain the differences between them.
Box-sizing: content-box and border-box.
Both calculate width and height of elements to expand within the content, but border-box includes padding and border.

In your own words, explain the difference between relative and absolute positioning.

Relative positioning will line elements to position on the page that is the relatively where they would go if it were in static position. Absolute positioning is similar but will reference the closest prior positioned element as a reference point to add or subtract the values of top, left, bottom, and right.

What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better.
Forget to include browser prefixes to css properties, thus not supporting those css in some browsers
Confusing position properties for content
Not adjusting elements/images to fit in media queries dimensions, thus having elements becoming squished

**Comment by J-Weeks** [comment]
Nice Good job.  You'll be using CSS a lot in the near future.
