### ISSUE TITLE
Update README.md to follow study-template

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/html-css-layout-study#19]
Specifically, see spa-study for a good example

**Comment by laurenfazah** [comment]
All set. Can be closed @jrhorn424

**Comment by gaand** [comment]
@jrhorn424 @laurenfazah Should this have been "base of study-template"?

**Comment by berziiii** [comment]
see with commit 7541127a3a738c9219a40b524031d498828d30ec. Okay to close @jrhorn424?

**Comment by gaand** [comment]
@berziiii Has `README.md` been updated from `study-template`?  It's not reflected in the commit you referenced.

**Comment by jrhorn424** [comment]
The evolution of this issue seems to have missed some changes. The boilerplate in this README is not currently up-to-date with the one in `study-template`, but the original intent of this issue has been addressed. Thanks for changing the title @gaand. I'll leave this open until the README is updated.

**Comment by berziiii** [comment]
I did refresh from study-template @gaand but if there were existing issues with the README.md structure then they most likely were not addressed.
