### ISSUE TITLE
Q&A Responses - Jen Weber

### ISSUE THREAD

**Issue by jenweber** [ga-wdi-boston/html-css-layout-study#7]
What are the different options for box-sizing? Explain the differences between them. Previously, an element's overall size varied with its border and padding.  With box sizing, the padding and border are factored in so that two boxes with the same width and different border properties will take up the same amount of space on the page.

In your own words, explain the difference between relative and absolute positioning. Relative positioning is like static except that repositioning the element does not affect the behavior of other elements around it. They do not flow to fill the space left behind. Absolute positioning is relative to another non-static element on the page.

What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better. 1. Forgetting to clear floats. 2. Trying to tack an absolute element onto something static. Using width when you should use max width to allow for varying screen sizes.

**Comment by J-Weeks** [comment]
Nice.  Good job, keep up the good work.
