### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/html-css-layout-study#8]
What is the different options for box-sizing? Explain the differences between them.
  - Before box-sizing, the width of an element was determined by it's content size unless otherwise denoted with margin and padding (a practice that was headache inducing because the designer had to figure out which margin and padding would be necessary to account for the content). Along comes box-sizing which automatically sets the width of an element to a predetermined size. The options for box-sizing are content-box and border-box. A content-box keyword is measured using only the content and excludes the padding and the margin. The border-box includes the padding and the margin.
In your own words, explain the difference between relative and absolute positioning.
  - Relative positioning acts like static position unless otherwise denoted (i.e top, left, width etc). Absolute shares these qualities but instead attaches itself to it's nearest positioned ancestor. If there is no nearest positioned ancestor...it attaches to the body and scrolls along. 
What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better. 
  - 1. Forgetting to clear floats. 2. Not adhering to 'top-down'(?) CSS. Forgetting that of keywords below another will take precedence over the one before it. 3. Not using the right positioning keyword to most effectively position an element.

**Comment by J-Weeks** [comment]
Nice Kevin, keep up the hot streak.
