### ISSUE TITLE
Response to question

### ISSUE THREAD

**Issue by dumplingpuff** [ga-wdi-boston/html-css-layout-study#9]
1) What is the different options for box-sizing? Explain the differences between them.

The default option will not calculate padding and border into the width and height, so the actual width of the element could larger than what it was originally set to.

On the other hand there is border box which includes the padding and border into width and height.  The box is has the actual width or height that you set it to, no math is needed to calculate differences.

2) In your own words, explain the difference between relative and absolute positioning.

Relative positioning is an element that is positioned relative to the view port or the window of the browser.
Absolute positioning is rather tricky.  It will position itself to the nearest positioned ancestor.  By positioned ancestor it means an element that has relative position. If no such ancestor exist or if the nearest ancestor is static position, it would escape and position itself relative to the view port.

3) What are three "gotchas" when working with CSS layouts? "Gotchas" are common mistakes that are easy to make, even if you know better differences between them.

1. Not using a clear fix when a floated object overflows.
2. Knowing when to use absolute positioning and how it interacts with static position.
3. Using percentage size on something like a side-bar.  Sometimes you can have weird text-wrapping that you don't want.

**Comment by J-Weeks** [comment]
Good job.  Keep up the good work.
